import type { AiToolsProvider } from "../application/ai-tools.provider.js";
import type { AiToolType, RunAiToolResponse } from "../types/ai-tool.type.js";

export class MockAiToolsService implements AiToolsProvider {
  async run(tool: AiToolType, input: string): Promise<RunAiToolResponse> {
    const cleanInput = input.trim();

    switch (tool) {
      case "cv-reviewer":
        return {
          tool,
          result: this.reviewCv(cleanInput),
        };

      case "code-explainer":
        return {
          tool,
          result: this.explainCode(cleanInput),
        };

      case "email-writer":
        return {
          tool,
          result: this.writeEmail(cleanInput),
        };

      case "content-generator":
        return {
          tool,
          result: this.generateContent(cleanInput),
        };

      case "business-idea-generator":
        return {
          tool,
          result: this.generateBusinessIdea(cleanInput),
        };

      case "summarizer":
        return {
          tool,
          result: this.summarize(cleanInput),
        };

      case "translator":
        return {
          tool,
          result: this.translate(cleanInput),
        };

      default:
        return {
          tool,
          result: "Tool is not supported yet.",
        };
    }
  }

  private reviewCv(input: string) {
    return `CV Review Result

Strengths:
- Your CV has a clear starting point and can be improved into a stronger professional profile.
- The content already gives useful context about your background.
- Your experience and skills can be positioned better for the target role.

Improvements:
- Add a stronger professional summary at the top.
- Use bullet points with measurable impact.
- Match your skills with the role you are applying for.
- Keep formatting clean, consistent, and easy to scan.

Suggested Summary:
A motivated candidate with practical experience and a strong interest in technology, problem solving, and product development. Able to learn quickly, work collaboratively, and contribute to real-world projects.

Input reviewed:
${input}`;
  }

  private explainCode(input: string) {
    return `Code Explanation

Overview:
This code is being analyzed in Mock Mode.

What it does:
- Reads the provided code or technical input.
- Identifies the main logic.
- Explains the purpose in simple terms.
- Highlights possible improvements.

Suggestion:
- Check naming consistency.
- Keep functions small and focused.
- Add error handling where needed.
- Add comments only for complex logic.

Code/input reviewed:
${input}`;
  }

  private writeEmail(input: string) {
    return `Generated Email

Subject: Follow Up

Hello,

I hope you are doing well.

I am writing to follow up regarding the following matter:

${input}

Please let me know if there is any update or additional information needed.

Thank you.

Best regards,`;
  }

  private generateContent(input: string) {
    return `Generated Content

Title:
${input}

Caption:
Turn your idea into something clear, useful, and ready to share. With the right message, your content can attract attention, explain value, and encourage people to take action.

Key Points:
- Clear message
- Strong opening
- Simple value proposition
- Direct call to action`;
  }

  private generateBusinessIdea(input: string) {
    return `Business Idea

Idea:
An AI-powered service based on: ${input}

Target Users:
- Students
- Freelancers
- Small business owners
- Early-stage startup founders

Problem:
Many users need faster ways to create, analyze, and improve their work without spending too much time.

Solution:
Build a simple AI tool that helps users complete tasks faster with guided input and instant output.

Monetization:
- Free limited plan
- Monthly subscription
- Premium templates
- Team plan`;
  }

  private summarize(input: string): string {
    const preview =
      input.length > 300 ? `${input.slice(0, 300)}...` : input;

    return `Summary

Main Idea:
${preview}

Key Takeaways:
- The text contains information that can be simplified.
- The main points should be presented clearly.
- A shorter version helps users understand faster.

Short Summary:
This content explains an idea or information that can be condensed into clear, practical points.`;
  }

  private translate(input: string): string {
    return `Translation Result

${input}

---

Mock Translation

This is a placeholder translation generated by ALVIRA Mock AI.

When OpenAI Provider is enabled, this tool will automatically produce real multilingual translations while preserving tone, grammar, and context.`;
  }
}

