import type { AiToolsProvider } from "../application/ai-tools.provider.js";
import type { AiToolType, RunAiToolResponse } from "../types/ai-tool.type.js";

export class MockAiToolsService implements AiToolsProvider {
  async run(tool: AiToolType, input: string): Promise<RunAiToolResponse> {
    const cleanInput = input.trim();

    switch (tool) {
      case "cv-reviewer":
        return { tool, result: this.reviewCv(cleanInput) };

      case "code-explainer":
        return { tool, result: this.explainCode(cleanInput) };

      case "email-writer":
        return { tool, result: this.writeEmail(cleanInput) };

      case "content-generator":
        return { tool, result: this.generateContent(cleanInput) };

      case "business-idea-generator":
        return { tool, result: this.generateBusinessIdea(cleanInput) };

      case "summarizer":
        return { tool, result: this.summarize(cleanInput) };

      case "translator":
        return { tool, result: this.translate(cleanInput) };

      case "business-analyzer":
        return { tool, result: this.analyzeBusiness(cleanInput) };

      case "image-prompter":
        return { tool, result: this.generateImagePrompt(cleanInput) };

      default:
        return { tool, result: "Tool is not supported yet." };
    }
  }

  private reviewCv(input: string): string {
    return `CV Review Result

Strengths:
- Your CV has a clear starting point and can be improved into a stronger professional profile.
- The content already gives useful context about your background.
- Your experience and skills can be positioned better for the target role.

Improvements:
- Add a stronger professional summary at the top.
- Use bullet points with measurable impact.
- Match your skills with the role you are applying for.
- Keep formatting clean, consistent, and easy to scan.

Suggested Summary:
A motivated candidate with practical experience and a strong interest in technology, problem solving, and product development. Able to learn quickly, work collaboratively, and contribute to real-world projects.

Input reviewed:
${input}`;
  }

  private explainCode(input: string): string {
    return `Neural Code Studio Report

Overview
The submitted code has been analyzed successfully.

Potential Issues
• Variable names could be more descriptive.
• Missing validation or error handling.
• Consider extracting repeated logic.
• Add comments only where business logic is complex.

Suggestions
✓ Use smaller functions.
✓ Follow consistent naming.
✓ Remove duplicated code.
✓ Improve formatting.
✓ Add unit tests.

Estimated Complexity
Time Complexity: O(n)
Space Complexity: O(1)

Submitted Code
${input}

Analysis completed successfully in Mock AI Mode.`;
  }

  private writeEmail(input: string): string {
    return `Generated Email

Subject: Follow Up

Hello,

I hope you are doing well.

I am writing to follow up regarding the following matter:

${input}

Please let me know if there is any update or additional information needed.

Thank you.

Best regards,`;
  }

  private generateContent(input: string): string {
    return `Generated Content

Title:
${input}

Caption:
Turn your idea into something clear, useful, and ready to share. With the right message, your content can attract attention, explain value, and encourage people to take action.

Key Points:
- Clear message
- Strong opening
- Simple value proposition
- Direct call to action`;
  }

  private generateBusinessIdea(input: string): string {
    return `Business Idea

Idea:
An AI-powered service based on: ${input}

Target Users:
- Students
- Freelancers
- Small business owners
- Early-stage startup founders

Problem:
Many users need faster ways to create, analyze, and improve their work without spending too much time.

Solution:
Build a simple AI tool that helps users complete tasks faster with guided input and instant output.

Monetization:
- Free limited plan
- Monthly subscription
- Premium templates
- Team plan`;
  }

  private summarize(input: string): string {
    const preview = input.length > 300 ? `${input.slice(0, 300)}...` : input;

    return `Summary

Main Idea:
${preview}

Key Takeaways:
- The text contains information that can be simplified.
- The main points should be presented clearly.
- A shorter version helps users understand faster.

Short Summary:
This content explains an idea or information that can be condensed into clear, practical points.`;
  }

  private translate(input: string): string {
    return `Translation Result

${input}

---

Mock Translation

This is a placeholder translation generated by ALVIRA Mock AI.

When OpenAI Provider is enabled, this tool will automatically produce real multilingual translations while preserving tone, grammar, and context.`;
  }

  private analyzeBusiness(input: string): string {
    return `Business Opportunity Analysis

Business Idea
${input}

Market Potential
★★★★☆

Strengths
• Clear customer problem
• Easy to validate with an MVP
• Can scale through digital channels

Weaknesses
• Competitive market
• Requires strong branding

Target Customers
• Students
• Professionals
• Small businesses

Revenue Streams
• Subscription
• One-time purchase
• Premium plans

Recommendation
Proceed with an MVP and validate demand through early adopters before investing heavily.`;
  }

  private generateImagePrompt(input: string): string {
    return `AI Image Prompt Studio

Main Prompt:
${input}, ultra detailed, professional composition, cinematic lighting, high contrast, sharp focus, premium visual style, modern design, 8k quality

Style:
Modern, polished, high-end, visually striking

Lighting:
Cinematic soft lighting with subtle glow and depth

Camera:
Three-quarter perspective, balanced framing, clean composition

Negative Prompt:
low quality, blurry, distorted, bad anatomy, messy layout, extra objects, unreadable text, watermark, oversaturated, noisy image

Recommended Platforms:
- Midjourney
- DALL·E
- Stable Diffusion
- Leonardo AI

Prompt Tip:
Use this prompt as a base, then add aspect ratio, style reference, and brand colors depending on your target platform.`;
  }
}
